### ISSUE TITLE
[FE] 상품 상세 조회 구현

### ISSUE THREAD

**Issue by jun108059** [jun108059/daangn-market#12]
## ✍🏻 Description

상품 상세 조회 구현

## ✅ To-Do

- [ ] [FE] Vue 상품 상세 조회 컴포넌트 개발
- [ ] [FE] axios 비동기 호출
- [ ] [BE] 상품 상세조회 API 개발
