### ISSUE TITLE
Docker MySQL 서버 구성

### ISSUE THREAD

**Issue by jun108059** [jun108059/daangn-market#19]
## ✍🏻 Description

H2 DB를 MySQL 서버로 구성합니다.

## ✅ To-Do

- [x] docker-compose 생성
- [x] docker 기반 MySQL 구성
- [x] 환경 설정 및 계정 정보는 `env` 파일로 구성해서 숨기기
