### ISSUE TITLE
[BE] 상품 검색 API

### ISSUE THREAD

**Issue by jun108059** [jun108059/daangn-market#28]
## ✍🏻 Description

상품명 + 지역 검색 API를 개발합니다.

Description | Method | Endpoint | Page
-- | -- | -- | --
상품 검색 (지역) | `GET` | /api/v1/product/search | 홈 → 검색버튼

## ✅ To-Do

- [x] Controller GetMapping 개발
- [x] 상품명+지역 필터 검색 로직 개발
- [x] JPA method 추가

## 📨 ETC

Back-Log : 검색 성능 개선하기
