### ISSUE TITLE
CI/CD 구축

### ISSUE THREAD

**Issue by jun108059** [jun108059/daangn-market#3]
## Description

[github action](https://docs.github.com/ko/actions) CI/CD 환경을 구축합니다.
AWS EC2, S3, CodeDeploy를 연동하여 서버를 구성합니다.

## To-Do

- [ ] Github Action CI 스크립트 작성
- [ ] AWS EC2 생성
- [ ] AWS S3, CodeDeploy 연동
- [ ] Github Action CD 스크립트 작성
