### ISSUE TITLE
[FE] 상품 Home 페이지 구성

### ISSUE THREAD

**Issue by jun108059** [jun108059/daangn-market#43]
## ✍🏻 Description

로그인 완료 후 landing되는 Home 페이지를 구성합니다.

## ✅ To-Do

- [x] 로그인 정보 기반 토큰 Header에 포함
- [x] 상품 판매 게시글 리스트 구성
- [x] 검색, 햄버거바(카테고리 선택 페이지 Landing) 구현
- [x] 상품 판매 게시글 등록 버튼 및 CTA
- [x] 나의 당근 페이지 버튼 및 CTA
