### ISSUE TITLE
[FE] 프로필 수정 페이지

### ISSUE THREAD

**Issue by jun108059** [jun108059/daangn-market#44]
## ✍🏻 Description

나의 당근 → 프로필 수정 페이지를 구성합니다.

## ✅ To-Do

- [ ] 닉네임, 프로필사진 변경 CTA
- [ ] 수정 가능/완료 배경색 변경 기능
- [ ] 프로필사진 변경 → 앨범에서 선택/프로필 사진 삭제 메뉴(알림?) 활성화
