### ISSUE TITLE
[FE] 회원가입(시작하기) 페이지 

### ISSUE THREAD

**Issue by jun108059** [jun108059/daangn-market#50]
## ✍🏻 Description

회원가입 페이지를 개발합니다.

<img width="200" alt="회원가입1" src="https://user-images.githubusercontent.com/42997924/219058041-41a5b95a-8ab0-466b-b7bf-0b980f08be34.gif">

## ✅ To-Do

- [ ] getting start 페이지 → 시작하기 페이지 연결
- [ ] 지역 select box 추가
- [ ] 회원가입 입력 폼 만들기
- [ ] submit 시 회원가입 API 호출
