### ISSUE TITLE
[FE] 카테고리 조회 페이지

### ISSUE THREAD

**Issue by jun108059** [jun108059/daangn-market#52]
## ✍🏻 Description

메인 홈 → 카테고리 조회 페이지를 구성합니다.

<img width="250" alt="스크린샷 2023-03-03 오전 6 45 11" src="https://user-images.githubusercontent.com/42997924/222563919-589a1b08-bda1-4154-8f5d-73b9b1226a3f.png">

## ✅ To-Do

- [ ] 카테고리 별 이미지 추가
- [ ] 카테고리 조회 API 호출
- [ ] 뒤로가기 기능
- [ ] 카테고리 선택 시 상품 리스트 조회 페이지 landing
